---
- name: Brownfield Device Credential Playbook Generator Example
  hosts: localhost
  gather_facts: false
  vars_files:
    - credentials.yml
  tasks:
    - name: Generate YAML playbook for host port onboarding workflow manager
        which includes all fabric sites's host port onboarding details
      cisco.dnac.brownfield_sda_host_port_onboarding_playbook_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        state: gathered
        config:
          - generate_all_configurations: true

    - name: Generate YAML Configuration with File Path specified
      cisco.dnac.brownfield_sda_host_port_onboarding_playbook_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        state: gathered
        config:
          - generate_all_configurations: true
            file_path: "host_onboarding_playbook.yml"

    - name: Generate YAML Configuration with specific component port assignments filters
      cisco.dnac.brownfield_sda_host_port_onboarding_playbook_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        state: gathered
        config:
          - generate_all_configurations: false
            file_path: "host_onboarding_playbook.yml"
            component_specific_filters:
              components_list: ["port_assignments"]
              port_assignments:
                fabric_site_name_hierarchy:
                  - "Global/Site_India/Karnataka/Bangalore"

    - name: Generate YAML Configuration with specific component port channels filters
      cisco.dnac.brownfield_sda_host_port_onboarding_playbook_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        state: gathered
        config:
          - generate_all_configurations: false
            file_path: "host_onboarding_playbook.yml"
            component_specific_filters:
              components_list: ["port_channels"]
              port_channels:
                fabric_site_name_hierarchy:
                  - "Global/Site_India/Karnataka/Bangalore"

    - name: Generate YAML Configuration with specific component wireless ssids filters
      cisco.dnac.brownfield_sda_host_port_onboarding_playbook_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        state: gathered
        config:
          - generate_all_configurations: false
            file_path: "host_onboarding_playbook.yml"
            component_specific_filters:
              components_list: ["wireless_ssids"]
              wireless_ssids:
                fabric_site_name_hierarchy:
                  - "Global/Site_India/Karnataka/Bangalore"
