---
config:
- cli_transport: ssh
  compute_device: false
  enable_password: null
  extended_discovery_info: null
  http_password: null
  http_port: null
  http_secure: null
  http_username: null
  ip_address_list:
  - 205.1.1.10
  hostname_list:
  - TB3-SJC-BORDER-01.autoagni1.com
  mac_address_list: null
  netconf_port: 830
  password: null
  serial_number_list:
  - FCW2334D0W1
  snmp_auth_passphrase: null
  snmp_auth_protocol: null
  snmp_mode: null
  snmp_priv_passphrase: null
  snmp_priv_protocol: null
  snmp_ro_community: null
  snmp_rw_community: null
  snmp_retry: 3
  snmp_timeout: 5
  snmp_username: null
  snmp_version: v2
  update_mgmt_ipaddresslist: null
  username: null
  role: null
  device_resync: null
  reboot_device: null
  credential_update: null
  export_device_details_limit: 500
  resync_device_count: 200
  resync_max_timeout: 600
  force_sync: null
  clean_config: null
  add_user_defined_field: null
  update_interface_details: null
  export_device_list: null
  provision_wired_device: null
