---
config:
- device_type: Cisco Catalyst C9500-48Y4C Switch
  family: Switches and Hubs
  series: Cisco Catalyst 9500 Series Switches
  role: BORDER ROUTER
  role_source: MANUAL
  hostname: TB4-BORDER-1.autoagni1.com
  management_ip_address: 206.1.2.1
  serial_number: FDO243417YM
  mac_address: 8c:94:1f:ab:fa:a0
  platform_id: C9500-48Y4C
  device_id: 8eca9f20-e8c7-4550-b2e0-8e92e3e843f4
  instance_uuid: 8eca9f20-e8c7-4550-b2e0-8e92e3e843f4
  instance_tenant_id: 67e6885ba7e51e7021a8a263
  software_type: IOS-XE
  software_version: 17.12.20240524:165410
  description: Cisco IOS Software [Dublin], Catalyst L3 Switch Software (CAT9K_IOSXE),
    Experimental Version 17.12.20240524:165410 [V1712_4PRD4_FC2:/nobackup/mcpre/s2c-build-ws
    101] Copyright (c) 1986-2024 by Cisco Systems, Inc. Compiled Fri 24-May-24 09:55
    by mcpre netconf enabled
  device_support_level: Supported
  reachability_status: Ping Reachable
  reachability_failure_reason: Partial Collection Failure
  collection_status: Partial Collection Failure
  collection_interval: Global Default
  management_state: Managed
  managed_atleast_once: true
  inventory_status_detail: '<status><general code="FAILED_FEAT"/><failed_features
    names="90 features seem to have failed : Please check the credentials provided."
    code="CLI_AUTH_ERROR"/><failed_features names="com.cisco.enc.feature.Fetch Device
    Config IOS" code="UNKNOWN"/><topCause code="CLI_AUTH_ERROR"/>

    </status>'
  last_update_time: 1769065759940
  last_updated: '2026-01-22 07:09:19'
  last_managed_resync_reasons: Periodic
  last_device_resync_start_time: '2026-01-22 07:00:36'
  reasons_for_device_resync: Periodic
  reasons_for_pending_sync_requests: null
  pending_sync_requests_count: '0'
  sync_requested_by_app: null
  dns_resolved_management_address: 206.1.2.1
  memory_size: NA
  line_card_count: '0'
  line_card_id: null
  interface_count: '0'
  up_time: 283 days, 1:14:44.91
  uptime_seconds: 24526360
  boot_date_time: '2025-04-14 05:55:19'
  snmp_contact: null
  snmp_location: null
  location: null
  location_name: null
  vendor: Cisco
  ap_manager_interface_ip: null
  associated_wlc_ip: null
  ap_ethernet_mac_address: null
  error_code: CLI-AUTH-ERROR
  error_description: 'NCIM12007: CLI credentials for this device do not match. Please
    ensure correct credentials are provided in global credentials or in discovery
    job. You can update the device credentials using update credentials option.'
  tag_count: '0'
  tunnel_udp_port: null
  waas_device_mode: null
- device_type: Cisco Catalyst 9300 Switch
  family: Switches and Hubs
  series: Cisco Catalyst 9300 Series Switches
  role: ACCESS
  role_source: AUTO
  hostname: TB3-BGL-EDGE2.autoagni1.com
  management_ip_address: 205.1.2.67
  serial_number: FJC2413E16S
  mac_address: 5c:a6:2d:6b:a3:00
  platform_id: C9300-48P
  device_id: 82b5f085-aff5-4d9a-8b3e-e71a8fd2d48d
  instance_uuid: 82b5f085-aff5-4d9a-8b3e-e71a8fd2d48d
  instance_tenant_id: 67e6885ba7e51e7021a8a263
  software_type: IOS-XE
  software_version: 17.12.3
  description: 'Cisco IOS Software [Dublin], Catalyst L3 Switch Software (CAT9K_IOSXE),
    Version 17.12.3, RELEASE SOFTWARE (fc7) Technical Support: http://www.cisco.com/techsupport
    Copyright (c) 1986-2024 by Cisco Systems, Inc. Compiled Wed 20-Mar-24 15:40 by
    mcpre netconf enabled'
  device_support_level: Supported
  reachability_status: Reachable
  reachability_failure_reason: null
  collection_status: Managed
  collection_interval: Global Default
  management_state: Managed
  managed_atleast_once: true
  inventory_status_detail: <status><general code="SUCCESS"/></status>
  last_update_time: 1769077158824
  last_updated: '2026-01-22 10:19:18'
  last_managed_resync_reasons: Periodic
  last_device_resync_start_time: '2026-01-22 10:18:00'
  reasons_for_device_resync: Periodic
  reasons_for_pending_sync_requests: null
  pending_sync_requests_count: '0'
  sync_requested_by_app: null
  dns_resolved_management_address: 205.1.2.67
  memory_size: NA
  line_card_count: '0'
  line_card_id: null
  interface_count: '0'
  up_time: 139 days, 23:22:50.76
  uptime_seconds: 12153041
  boot_date_time: '2025-09-04 10:57:18'
  snmp_contact: null
  snmp_location: null
  location: null
  location_name: null
  vendor: Cisco
  ap_manager_interface_ip: null
  associated_wlc_ip: null
  ap_ethernet_mac_address: null
  error_code: null
  error_description: null
  tag_count: '0'
  tunnel_udp_port: null
  waas_device_mode: null
